### ISSUE TITLE
model size

### ISSUE THREAD

**Issue by Fightinging1997** [AWCXV/MUFusion#2]
Hello author, the Model size paper mentions 2.1240M, but from the code, whether you use tno or roadscene, the model size is 554M, which is very different. If I want to quote your model, which fusion model size should be used? What?

**Comment by AWCXV** [comment]
Thank you for your attention. The model size in my paper refers to the volume of the "xxx.model" file, which is 2100KB (2MB+) in my code repository and it is consistent with my paper. Please check the files for more information.
