### ISSUE TITLE
Fusion results color problems

### ISSUE THREAD

**Issue by yaoliu0803** [AWCXV/MUFusion#4]
Hi. Thank you for sharing. I want to reproduce the effect of color images in the project, and I want to achieve the effect of the three channels output. But the result image in the output folder of your project directory turns out to be an 8 bits gray image. I would like to ask how to modify the code to produce the effect I want. If you see, please reply to me as soon as possible! Thank you very much again!

**Comment by AWCXV** [comment]
Thank you for your comments. We have provided the rgb inference in each folder of the subtask. Please refer to "test_image_rgb.py" for more detail. And, yes, the original code can only deliver grayscale output. Thus, we achieve this objective based on the ycbcr transformation.
